### ISSUE TITLE
[Bug] Font issues with OptiFine

### ISSUE THREAD

**Issue by bowser0000** [Fix3dll/SkyblockAddons#33]
### Bug Description

1.8.9+227 and above causes issues when used with Optifine. Easily visible in the scoreboard when you're in the Village or Glacite Tunnels.

![](https://i.imgur.com/DXuOLPd.png)

### SBA Version

1.9.0-beta.2+242

### Other Installed Mods

OptiFine M5

### Operating System

Windows 10

### Crash Report

N/A

**Comment by Fix3dll** [comment]
@bowser0000 
![image](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/f07b5bc6-7e45-4347-b607-747a29c4a57c)
![image](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/65ddf3e9-cf71-4539-b0ad-bdf439223697)
(Enviroment with just SBA and Optifine)
I cant reproduce. Could be about optifine settings or anything?

**Comment by Fix3dll** [comment]
@bowser0000 Could you try again with the latest build?

**Comment by bowser0000** [comment]
Seems to be fine with the latest build

**Comment by Fix3dll** [comment]
If the font breaks again, you can reopen issue.

**Comment by Erwanito92** [comment]
Fonts broke again in 1.9.0-beta.4

**Comment by Fix3dll** [comment]
> Fonts broke again in 1.9.0-beta.4

Could you share more detail? I cant reproduce.

**Comment by bowser0000** [comment]
I can also recreate with only SBA 1.9.0-beta.4+257 and OptiFine M5.

NEU Stats (game wouldn't launch without Skytils):
```md
# System Stats
[OS][Windows 10]
[CPU][16x AMD Ryzen 7 7800X3D 8-Core Processor ]
[Display][2560x1377 (NVIDIA Corporation)]
[GPU][NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2]
[GPU Driver][4.6.0 NVIDIA 551.23]
[Maximum Memory][31937MB]
[Shaders][TRUE]
# Java Stats
[Java][1.8.0_51 64bit]
[Memory][ 20% 858/4096MB]
[Memory Allocated][ 100% 4096MB]
# Game Stats
[FPS][165]
[Loaded Mods][7]
[Forge][11.15.1.2318]
[Optifine][TRUE]
# Neu Settings
[On SkyBlock][TRUE]
[Mod Version][2.2.1+c266561e]
[Version Id][20201]
[SB Profile][Watermelon]
# Repo Stats
[Last Commit][5cc0b0167eefcc7c2e16f90a960ccfd57eb3eb0c]
[Repo Location][https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/tree/prerelease]
[Using Backup][false]
[Loaded Items][6282]
[Lowest Bin API Location][moulberry.codes]
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9.jar (11.15.1.2318)]
[Essential][Essential (forge_1.8.9).processed.jar (1.3.1.3+g88238d7752)]
[NotEnoughUpdates][NotEnoughUpdates-2.2.1.jar (2.2.1+c266561e)]
[SkyblockAddons Unofficial][SkyblockAddons-1.9.0-beta.4+257-for-MC-1.8.9.jar (1.9.0-beta.4+257)]
[Skytils][Skytils-1.9.4.jar (1.9.4)]
```

**Comment by Fix3dll** [comment]
> NEU Stats (game wouldn't launch without Skytils):

@bowser0000 at least should be open without Skytils with 1.9.0-beta.5.

**Comment by Erwanito92** [comment]
NEU Stats with SkyblockAddons 1.9.0-beta.5 and NEU 2.2.1 only, also no textures packs:
```md
# System Stats
[OS][Windows 10]
[CPU][24x 12th Gen Intel(R) Core(TM) i7-12800HX]
[Display][1920x1009 (NVIDIA Corporation)]
[GPU][NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2]
[GPU Driver][4.6.0 NVIDIA 552.22]
[Maximum Memory][32469MB]
[Shaders][TRUE]
# Java Stats
[Java][1.8.0_51 64bit]
[Memory][ 31% 1280/4096MB]
[Memory Allocated][ 82% 3392MB]
# Game Stats
[FPS][119]
[Loaded Mods][5]
[Forge][11.15.1.2318]
[Optifine][TRUE]
# Neu Settings
[On SkyBlock][TRUE]
[Mod Version][2.2.1+c266561e]
[Version Id][20201]
[SB Profile][Lemon]
# Repo Stats
[Last Commit][1aed3a28757e5c0e87b3040e406b8243461c09e1]
[Repo Location][https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/tree/prerelease]
[Using Backup][false]
[Loaded Items][6291]
[Lowest Bin API Location][moulberry.codes]
# Repo Files
[.gitattributes]
[.github][1]
[.gitignore]
[.vscode][2]
[constants][28]
[enforced_values][2]
[items][6291]
[LICENSE]
[mobs][221]
[neu-items-master.zip]
[README.md]
[update.json]
[update.json.asc]
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9.jar (11.15.1.2318)]
[NotEnoughUpdates][NotEnoughUpdates-2.2.1.jar (2.2.1+c266561e)]
[SkyblockAddons Unofficial][SkyblockAddons-1.9.0-beta.5+266-for-MC-1.8.9.jar (1.9.0-beta.5+266)]
```

Happens in the chat, the sidebar, tooltips.
I guess some icons are the problem? Broken text always appears after one. Also, it looks like it's not the case for some of them.
For non bold text, the first column of pixels on the left of each character is not rendering.
![gitchy text](https://github.com/Fix3dll/SkyblockAddons/assets/89878127/8c3b1baa-1f35-4c7a-95c2-4f3c03145102)

**Comment by Fix3dll** [comment]
@bowser0000 @Erwanito92 could you try latest build?

**Comment by bowser0000** [comment]
Still broken on builds 279 and 280.

**Comment by Erwanito92** [comment]
I confirm this is still broken with the 1.9.0-beta.7.1 version.

**Comment by Fix3dll** [comment]
```md
# System Stats
[OS][Windows 10]
[CPU][16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz]
[Display][1920x1017 (NVIDIA Corporation)]
[GPU][NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2]
[GPU Driver][4.6.0 NVIDIA 552.22]
[Maximum Memory][16128MB]
[Shaders][TRUE]
# Java Stats
[Java][1.8.0_412 64bit]
[Memory][ 75% 1540/2048MB]
[Memory Allocated][ 100% 2048MB]
# Game Stats
[FPS][40]
[Loaded Mods][7]
[Forge][11.15.1.2318]
[Optifine][TRUE]
# Neu Settings
[On SkyBlock][TRUE]
[Mod Version][2.2.2+2767ef49]
[Version Id][20202]
[SB Profile][Cucumber]
# Repo Stats
[Last Commit][84756f951e8627d1b55fc95d7a429b08f64c678b]
[Repo Location][https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/tree/prerelease]
[Using Backup][false]
[Loaded Items][6450]
[Lowest Bin API Location][moulberry.codes]
# Repo Files
[.gitattributes]
[.github][1]
[.gitignore]
[.vscode][2]
[constants][28]
[enforced_values][2]
[items][6450]
[LICENSE]
[mobs][221]
[neu-items-master.zip]
[README.md]
[update.json]
[update.json.asc]
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9-universal.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9-universal.jar (11.15.1.2318)]
[Essential][Essential (forge_1.8.9).jar (1.3.2.3+g6a2d13e09b)]
[NotEnoughUpdates][NotEnoughUpdates-2.2.2.jar (2.2.2+2767ef49)]
[SkyblockAddons Unofficial][SkyblockAddons-1.9.0-beta.8-for-MC-1.8.9.jar (1.9.0-beta.8)]
[Skytils][Skytils-1.9.4.jar (1.9.4)]
```
@Erwanito92 @bowser0000 I tried to open shaders like you and downgraded Optifine to M5 but still i cant reproduce.
![2024-05-10_13 08 37](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/f6311b0d-7d8b-4360-976e-01cc14030e87)
I don't think it's related, but the only thing I haven't tried is the Java version difference.
I removed `-Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US` parameters too but still cant reproduce.

**Comment by Fix3dll** [comment]
@bowser0000 I didn't mean that. Chroma working as shader and its not related with Java version. I mean i still can't reproduce the glitch. Could you try with `-Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US` Java parameters? I want to be sure if it is related to the language.

**Comment by Triggered0** [comment]
Still having the issue with latest beta.
```md
# System Stats
[OS][Windows 10]
[CPU][32x 13th Gen Intel(R) Core(TM) i9-13900HX]
[Display][2560x1600 (NVIDIA Corporation)]
[GPU][NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2]
[GPU Driver][4.6.0 NVIDIA 552.22]
[Maximum Memory][32452MB]
[Shaders][TRUE]
# Java Stats
[Java][1.8.0_51 64bit]
[Memory][ 37% 1532/4096MB]
[Memory Allocated][ 53% 2208MB]
# Game Stats
[FPS][245]
[Loaded Mods][21]
[Forge][11.15.1.2318]
[Optifine][TRUE]
# Neu Settings
[On SkyBlock][TRUE]
[Mod Version][2.2.2+2767ef49]
[Version Id][20202]
[SB Profile][Mango]
# Repo Stats
[Last Commit][f0364e12d2be44383521559a8210746d62d450a7]
[Repo Location][https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/tree/prerelease]
[Using Backup][false]
[Loaded Items][6451]
[Lowest Bin API Location][moulberry.codes]
# Repo Files
[.gitattributes]
[.github][1]
[.gitignore]
[.vscode][2]
[constants][28]
[enforced_values][2]
[items][6451]
[LICENSE]
[mobs][221]
[neu-items-master.zip]
[README.md]
[update.json]
[update.json.asc]
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9.jar (11.15.1.2318)]
[Dungeons Guide][minecraft.jar (unknown)]
[Essential][Essential (forge_1.8.9).processed.jar (1.3.2.3+g6a2d13e09b)]
[OneConfig][OneConfig (1.8.9-forge).jar (0.2.2-alpha201)]
[BazaarNotifier][BazaarNotifier-1.7.2.jar (1.7.2)]
[Chatting][Chatting-1.8.9-forge-1.5.3.jar (1.5.3)]
[CrashPatch][CrashPatch-1.8.9-forge-2.0.0.jar (2.0.0)]
[ChatTriggers][ctjs-2.2.0-1.8.9.jar (2.2.0-1.8.9)]
[Dungeons Guide Loader][dungeonsguide-4.0.0-beta9.5-standalone.jar (4.0.0)]
[NotEnoughUpdates][NotEnoughUpdates-2.2.2.jar (2.2.2+2767ef49)]
[Odin][Odin-1.2.5.beta6.jar (1.2.5.beta6)]
[Patcher][Patcher-1.8.9 (1.8.9).jar (1.8.9)]
[PolySprint][PolySprint-1.8.9-forge-1.0.0.jar (1.0.0)]
[Gravy's Reward Claim][RewardClaim-1.0.5.jar (1.0.5)]
[SkyblockAddons Unofficial][SkyblockAddons-1.9.0-beta.8+295-for-MC-1.8.9.jar (1.9.0-beta.8+295)]
[SkyHanni][SkyHanni-0.25.Beta.24.jar (0.25.Beta.24)]
[Skytils][Skytils-1.9.4.jar (1.9.4)]
[SoopyV2Forge][soopyv2forge-1.1.jar (1.1)]
```
![image](https://github.com/Fix3dll/SkyblockAddons/assets/57991380/7fa27996-0446-427e-87f6-676fe42f485c)

**Comment by Fix3dll** [comment]
@Trîggered @bowser0000 @Erwanito92 Was the problem resolved with the latest build?

**Comment by Triggered0** [comment]
im still having the issue with the latest build.
```md
# System Stats
[OS][Windows 10]
[CPU][32x 13th Gen Intel(R) Core(TM) i9-13900HX]
[Display][2560x1600 (NVIDIA Corporation)]
[GPU][NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2]
[GPU Driver][4.6.0 NVIDIA 552.22]
[Maximum Memory][32452MB]
[Shaders][TRUE]
# Java Stats
[Java][1.8.0_51 64bit]
[Memory][ 37% 1532/4096MB]
[Memory Allocated][ 53% 2208MB]
# Game Stats
[FPS][245]
[Loaded Mods][21]
[Forge][11.15.1.2318]
[Optifine][TRUE]
# Neu Settings
[On SkyBlock][TRUE]
[Mod Version][2.2.2+2767ef49]
[Version Id][20202]
[SB Profile][Mango]
# Repo Stats
[Last Commit][f0364e12d2be44383521559a8210746d62d450a7]
[Repo Location][https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/tree/prerelease]
[Using Backup][false]
[Loaded Items][6451]
[Lowest Bin API Location][moulberry.codes]
# Repo Files
[.gitattributes]
[.github][1]
[.gitignore]
[.vscode][2]
[constants][28]
[enforced_values][2]
[items][6451]
[LICENSE]
[mobs][221]
[neu-items-master.zip]
[README.md]
[update.json]
[update.json.asc]
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9.jar (11.15.1.2318)]
[Dungeons Guide][minecraft.jar (unknown)]
[Essential][Essential (forge_1.8.9).processed.jar (1.3.2.3+g6a2d13e09b)]
[OneConfig][OneConfig (1.8.9-forge).jar (0.2.2-alpha201)]
[BazaarNotifier][BazaarNotifier-1.7.2.jar (1.7.2)]
[Chatting][Chatting-1.8.9-forge-1.5.3.jar (1.5.3)]
[CrashPatch][CrashPatch-1.8.9-forge-2.0.0.jar (2.0.0)]
[ChatTriggers][ctjs-2.2.0-1.8.9.jar (2.2.0-1.8.9)]
[Dungeons Guide Loader][dungeonsguide-4.0.0-beta9.5-standalone.jar (4.0.0)]
[NotEnoughUpdates][NotEnoughUpdates-2.2.2.jar (2.2.2+2767ef49)]
[Odin][Odin-1.2.5.beta6.jar (1.2.5.beta6)]
[Patcher][Patcher-1.8.9 (1.8.9).jar (1.8.9)]
[PolySprint][PolySprint-1.8.9-forge-1.0.0.jar (1.0.0)]
[Gravy's Reward Claim][RewardClaim-1.0.5.jar (1.0.5)]
[SkyblockAddons Unofficial][SkyblockAddons-1.9.0-beta.8+295-for-MC-1.8.9.jar (1.9.0-beta.8+295)]
[SkyHanni][SkyHanni-0.25.Beta.24.jar (0.25.Beta.24)]
[Skytils][Skytils-1.9.4.jar (1.9.4)]
[SoopyV2Forge][soopyv2forge-1.1.jar (1.1)]
```

![image](https://github.com/Fix3dll/SkyblockAddons/assets/57991380/6706e5f5-b560-475a-8961-1a7039eee552)

**Comment by bowser0000** [comment]
Still broken on build 296 as well. Last known working is beta.2+244
